version: '3.7'

services:
  sl-database:
    container_name: sl-database-dev
    image: sl-database-dev:0.1
    environment:
      POSTGRES_USER: sl-user
      POSTGRES_PASSWORD: sl-123
      PGDATA: /data/postgres
      POSTGRES_DB: sl-db
    volumes:
      - ./database/sl-data:/data/postgres
    ports:
      - "35432:5432"
    restart: unless-stopped
  sl-api:
    image: sl-api-dev:0.1
    container_name: sl-api-dev
    restart: always
    ports:
      - "38081:8081"
    environment:
      - URL_DATABASE=jdbc:postgresql://sl-database-dev:5432/sl-db
  sl-web:
    image: sl-web-dev:0.1
    container_name: sl-web-dev
    restart: always
    ports:
      - "33001:3001"
