
--QUERIES TO FIRST PRESENTATION
CREATE SCHEMA IF NOT EXISTS SL;
CREATE TABLE IF NOT EXISTS SL.CLIENT(
ID varchar(255) not null,
ADDRESS varchar(255),
DESCRIPTION varchar(255),
NAME varchar(255),
PHONE varchar(255),
UPDATED_AT timestamp(6),
CREATED_AT timestamp(6),
PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SL.CLIENT_DIFFERENCE(
ID varchar(255) not null,
CLIENT_ID varchar(255),
DESCRIPTION varchar(255),
DIFFERENCE_TYPE varchar(255),
DIFFERENCE_STATUS varchar(255),
AMOUNT real,
CREATED_AT timestamp(6),
UPDATED_AT timestamp(6),
PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SL.CURRENCY(
ID varchar(255) not null,
NAME varchar(255),
BUY_PRICE real,
SELL_PRICE real,
UPDATED_AT timestamp(6),
PRIMARY KEY (ID)
);

INSERT INTO SL.CURRENCY(ID, NAME, BUY_PRICE, SELL_PRICE, UPDATED_AT)
VALUES ('fa77a255-3c87-4baa-84a1-1821030e24c9','Dolar grande', 101, 102, NOW());
--WHERE NOT EXISTS (SELECT ID FROM SL.CURRENCY WHERE NAME = 'Dolar grande');

INSERT INTO SL.CURRENCY(ID, NAME, BUY_PRICE, SELL_PRICE, UPDATED_AT)
VALUES ('cf0ece59-4343-4b19-bbb5-dc28fc0d0f3b','Dolar chico', 201, 202, NOW());
--WHERE NOT EXISTS (SELECT ID FROM SL.CURRENCY WHERE NAME = 'Dolar chico');

INSERT INTO SL.CURRENCY(ID, NAME, BUY_PRICE, SELL_PRICE, UPDATED_AT)
VALUES ('9f294dab-b234-404b-8de9-9de0b9fe517b','Euro', 301, 302, NOW());
--WHERE NOT EXISTS (SELECT ID FROM SL.CURRENCY WHERE NAME = 'Euro');

INSERT INTO SL.CURRENCY(ID, NAME, BUY_PRICE, SELL_PRICE, UPDATED_AT)
VALUES ('f8f98478-5a7c-47aa-a473-ea044b7314b7','Real', 401, 402, NOW());
--WHERE NOT EXISTS (SELECT ID FROM SL.CURRENCY WHERE NAME = 'Real');

CREATE TABLE IF NOT EXISTS SL.NOTE(
ID varchar(255) not null,
COLOR varchar(255),
DESCRIPTION varchar(255),
CREATED_AT timestamp(6),
UPDATED_AT timestamp(6),
PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SL.PROVIDER(
ID varchar(255) not null,
ADDRESS varchar(255),
NAME varchar(255),
PHONE varchar(255),
UPDATED_AT timestamp(6),
CREATED_AT timestamp(6),
PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SL.SELLER(
ID varchar(255) not null,
DESCRIPTION varchar(255),
NAME varchar(255),
PHONE varchar(255),
UPDATED_AT timestamp(6),
CREATED_AT timestamp(6),
PRIMARY KEY (ID)
);

--QUERIES TO SECOUND PRESENTATION

--BUY_OPERATION
CREATE TABLE IF NOT EXISTS SL.BUY_OPERATION(
ID varchar(255) not null,
CLIENT_ID varchar(255),
CURRENCY_MULTI_BOX varchar(255),
PRICE real,
QUANTITY real,
PERCENT real,
TOTAL real,
OFFICE_CHECK boolean,
OPERATION_STATUS varchar(255),
RESERVE real,
CREATED_AT timestamp(6),
UPDATED_AT timestamp(6),
PRIMARY KEY (ID)
);
--SELL_OPERATION
CREATE TABLE IF NOT EXISTS SL.SELL_OPERATION(
ID varchar(255) not null,
CLIENT_ID varchar(255),
CURRENCY_MULTI_BOX varchar(255),
PRICE real,
QUANTITY real,
SUB_PROFIT real,
PROFIT real,
TOTAL real,
SELLER_ID varchar(255),
OPERATION_STATUS varchar(255),
CREATED_AT timestamp(6),
UPDATED_AT timestamp(6),
PRIMARY KEY (ID)
);
--MULTIBOX
CREATE TABLE IF NOT EXISTS SL.MULTIBOX(
ID varchar(255) not null,
UPDATED_AT timestamp(6),
CURRENCY_BOX varchar(255),
OPERATION_ID varchar(255),
OPERATION_TYPE varchar(255),
QUANTITY real,
QUANTITY_OPERATION real,
MULTI_BOX_STATUS varchar(255),
PRIMARY KEY (ID)
);
--BALANCE
CREATE TABLE IF NOT EXISTS SL.BALANCE(
ID varchar(255) not null,
PROFIT real,
OPERATION_ID varchar(255),
CREATED_AT timestamp(6),
UPDATED_AT timestamp(6),
PRIMARY KEY (ID)
);
--SELER_BOX
CREATE TABLE IF NOT EXISTS SL.SELER_BOX(
ID varchar(255) not null,
BALANCE_ID varchar(255),
NAME varchar(255),
DESCRIPTION varchar(255),
CREATED_AT timestamp(6),
UPDATED_AT timestamp(6),
PRIMARY KEY (ID)
);
--SELLER_COMMISSION
CREATE TABLE IF NOT EXISTS SL.SELLER_COMMISSION(
ID varchar(255) not null,
SELLER_ID varchar(255),
SELLER_COMMISSION_STATUS varchar(255),
PESOS real,
QUANTITY real,
PROFIT real,
CREATED_AT timestamp(6),
UPDATED_AT timestamp(6),
PRIMARY KEY (ID)
);