version: '3.7'

services:
  sl-database:
    container_name: sl-database-prod
    image: sl-database-prod:0.1
    environment:
      POSTGRES_USER: sl-user
      POSTGRES_PASSWORD: sl-123
      PGDATA: /data/postgres
      POSTGRES_DB: sl-db
    volumes:
      - ./database/sl-data:/data/postgres
    ports:
      - "25432:5432"
    restart: unless-stopped
  sl-api:
    image: sl-api-prod:0.1
    container_name: sl-api-prod
    restart: always
    ports:
      - "18081:8081"
    environment:
      - URL_DATABASE=jdbc:postgresql://sl-database-prod:5432/sl-db
  sl-web:
    image: sl-web-prod:0.1
    container_name: sl-web-prod
    restart: always
    ports:
      - "13001:3001"
